on:
  workflow_dispatch
  push:
    branches:
      - master
jobs:
  deploy-cdn:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, 'Bump version')"
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v1
        with:
          args: 'zip -r ./resources.zip . -i ./*/* -x ./.*/*'
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm i -D @altmp/upload-tool
      - run: |
          mkdir ./dist
          mv ./resources.zip ./dist/
      - run: npx alt-upload dist example-resources 1.0.0
        env:
          CI_UPLOAD_URL: ${{ secrets.CI_UPLOAD_URL }}
          CI_DEPLOY_TOKEN: ${{ secrets.CI_DEPLOY_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
