on:
  push:
    branches:
      - master
jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup server
        working-directory: server
        run: |
            sudo apt install jq -y
            mkdir -p data && mkdir -p modules && mkdir -p modules/js-module
            wget --no-cache -q -O ./altv-server https://cdn.altv.mp/server/release/x64_linux/altv-server
            wget --no-cache -q -O ./modules/js-module/libnode.so.72 https://cdn.altv.mp/js-module/release/x64_linux/modules/js-module/libnode.so.72
            wget --no-cache -q -O ./modules/js-module/libjs-module.so https://cdn.altv.mp/js-module/release/x64_linux/modules/js-module/libjs-module.so
            wget --no-cache -q -O ./modules/libcsharp-module.so https://cdn.altv.mp/coreclr-module/release/x64_linux/modules/libcsharp-module.so
            wget --no-cache -q -O ./AltV.Net.Host.dll https://cdn.altv.mp/coreclr-module/release/x64_linux/AltV.Net.Host.dll
            wget --no-cache -q -O ./AltV.Net.Host.runtimeconfig.json https://cdn.altv.mp/coreclr-module/release/x64_linux/AltV.Net.Host.runtimeconfig.json
            chmod +x ./altv-server && chmod +x ./start_server.sh
            APP_VERSION=$(cat package.json | jq .version -r)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.REGISTRY_IMG }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          workdir: server
          tags: "latest,${{ env.APP_VERSION }}"
